# Generated by Django 2.1.8 on 2019-06-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('IDR', 'IDR')], max_length=20),
        ),
        migrations.AlterField(
            model_name='provider',
            name='language',
            field=models.CharField(choices=[('English', 'ENGLISH'), ('Indonesian', 'INDONESIAN')], max_length=20),
        ),
    ]
